version = 0.1

[default.deploy.parameters]
stack_name = "marketlens-dev"
resolve_s3 = true
s3_prefix = "marketlens-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"dev\" ApiKeyValue=\"UBa92w4rAWm1JPSurcc4otfE7SPKKLXOlaqycEhx168\" SenderEmail=\"wakeenproduction@gmail.com\" GoogleClientId=\"placeholder-not-configured\" GoogleClientSecret=\"placeholder-not-configured\" CognitoCallbackDomain=\"d3qv7k78vm3pjm.cloudfront.net\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
