import { useState } from 'react';
import { Blocks, Check, Copy, Lock, RefreshCw } from 'lucide-react';
import type { BuildBrief } from '../types';
import type { UseBuildBriefResult } from '../hooks/useBuildBrief';
import './build-brief.css';

interface Props {
  buildBrief: UseBuildBriefResult;
  idea: string;
  /** Routes to the Pro upgrade path (handles anon sign-in upstream). */
  onUpgrade: () => void;
}

/* The product's own voice about its own limits — fixed copy, not model output,
   so the trust framing is consistent on every brief. */
const FOUNDATION_PRINCIPLES = [
  'Practice least privilege: give each piece only the access it needs.',
  'Prefer managed services over self-hosted where you can.',
  'Start on one cloud, not many.',
  'Choose secure defaults from day one.',
];
const LIMIT_STATEMENT =
  "AI isn't always right. Treat this as a starting point, not a vetted secure design. Get professional review before you build on it, especially on security.";

/* Complexity uses the report's saturation thresholds — higher means harder. */
function complexityColor(score: number): string {
  if (score <= 40) return 'var(--success)';
  if (score <= 65) return 'var(--warning)';
  return 'var(--danger)';
}

function formatGeneratedAt(iso: string | null): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function buildBriefMarkdown(brief: BuildBrief, idea: string): string {
  const L: string[] = [];
  L.push(`# Build Brief — ${idea}`);
  L.push('');
  if (!brief.isTechDominant) {
    L.push(
      '> This idea is not technology-dominant. The most it needs to start is a website and a way to take payments, and that is still a scalable foundation.',
    );
    L.push('');
  }
  L.push(`**Build complexity:** ${brief.complexityLabel} (${brief.complexityScore}/100)`);
  if (brief.complexityDrivers.length) {
    L.push(`Driven by ${brief.complexityDrivers.join(', ')}.`);
  }
  L.push(`**Effort:** ${brief.effort.timeframe} · ${brief.effort.teamShape}`);
  L.push('');

  if (brief.capabilities.length) {
    L.push('## Capabilities · build or buy');
    L.push('');
    for (const c of brief.capabilities) {
      L.push(`- **${c.name}** \`${c.buildOrBuy.toUpperCase()}\` · ${c.description}`);
      if (c.recommendation) L.push(`  - Recommended: ${c.recommendation}`);
    }
    L.push('');
  }

  if (brief.foundation.length) {
    L.push('## Foundation · vendor-neutral');
    L.push('');
    L.push('This is the foundation every major cloud gives you. Pick the one you are comfortable with.');
    L.push('');
    for (const f of brief.foundation) {
      L.push(`- **${f.primitive}** (${f.cloudExamples}) · ${f.why}`);
    }
    L.push('');
  }

  if (brief.mvpScope) {
    L.push('## MVP scope');
    L.push('');
    L.push(brief.mvpScope);
    L.push('');
  }

  if (brief.technicalRisks.length) {
    L.push('## Technical risks');
    L.push('');
    brief.technicalRisks.forEach((r, i) => {
      L.push(`${i + 1}. **${r.title}** · ${r.description}`);
    });
    L.push('');
  }

  L.push('## Foundations & limits');
  L.push('');
  for (const p of FOUNDATION_PRINCIPLES) L.push(`- ${p}`);
  L.push('');
  L.push(`> ${LIMIT_STATEMENT}`);
  L.push('');
  L.push('---');
  L.push('Generated by plinths · Build Brief');
  return L.join('\n');
}

/* ──────────────────────────────────────────────────────────
   Invitation — the CTA states (locked / idle) are a present,
   warm card, not a hidden accordion row.
   ────────────────────────────────────────────────────────── */

function Invite({
  locked,
  freeTaste,
  onGenerate,
  onUpgrade,
}: {
  locked?: boolean;
  freeTaste?: boolean;
  onGenerate?: () => void;
  onUpgrade?: () => void;
}) {
  return (
    <div className="bb-invite">
      {locked && (
        <div className="bb-invite-head">
          <span className="bb-pro">
            <Lock size={10} strokeWidth={2.5} aria-hidden />
            Pro
          </span>
        </div>
      )}
      <h3 className="bb-headline">
        {locked ? 'See what it would take to build this.' : 'Turn this idea into a build brief.'}
      </h3>
      <p className="bb-lead">
        Plain-English: the capabilities you would need, what to build versus buy, a
        vendor-neutral foundation to start on, rough effort, and the real risks.
        {locked ? '' : ' Grounded in this report.'}
      </p>
      {locked ? (
        <button type="button" className="bb-cta" onClick={onUpgrade}>
          Upgrade to Pro
        </button>
      ) : (
        <>
          {freeTaste && (
            <div className="bb-eyebrow" style={{ marginBottom: '0.75rem' }}>
              Your free build brief
            </div>
          )}
          <button type="button" className="bb-cta" onClick={onGenerate}>
            <Blocks size={14} strokeWidth={2} aria-hidden />
            Generate build brief
          </button>
        </>
      )}
    </div>
  );
}

function SkeletonState() {
  return (
    <div className="bb-skeleton" aria-hidden>
      <div className="bb-skel-strip">
        <div className="bb-skel-bar bb-skel-bar--badge" />
        <div className="bb-skel-bar bb-skel-bar--effort" />
      </div>
      <div className="bb-skel-block">
        <div className="bb-skel-bar bb-skel-bar--eyebrow" />
        <div className="bb-skel-bar bb-skel-bar--row" />
        <div className="bb-skel-bar bb-skel-bar--row" />
        <div className="bb-skel-bar bb-skel-bar--row bb-skel-bar--short" />
      </div>
    </div>
  );
}

function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <div className="bb-error">
      <p className="bb-error-msg">{message}</p>
      <button type="button" className="bb-retry" onClick={onRetry}>
        <RefreshCw size={13} strokeWidth={2} aria-hidden />
        Try again
      </button>
    </div>
  );
}

function BriefBody({
  brief,
  idea,
  generatedAt,
}: {
  brief: BuildBrief;
  idea: string;
  generatedAt: string | null;
}) {
  const [copied, setCopied] = useState(false);

  const copyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(buildBriefMarkdown(brief, idea));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard blocked */
    }
  };

  return (
    <div className="bb-brief">
      {/* ── Conclusion strip: how hard, how long, who ── */}
      {!brief.isTechDominant ? (
        <div className="bb-card bb-lowtech">
          <div className="bb-eyebrow">Not technology-dominant</div>
          <p className="bb-lowtech-text">
            This idea is not software-heavy. The most you need to start is a website and a
            way to take payments, and that is still a scalable foundation you can build on.
          </p>
        </div>
      ) : (
        <div className="bb-summary">
          <div className="bb-summary-cell">
            <div className="bb-eyebrow">Build complexity</div>
            <div className="bb-complexity">
              <span
                className="bb-complexity-dot"
                style={{ background: complexityColor(brief.complexityScore) }}
                aria-hidden
              />
              <span
                className="bb-complexity-label"
                style={{ color: complexityColor(brief.complexityScore) }}
              >
                {brief.complexityLabel}
              </span>
              <span className="bb-complexity-score">{brief.complexityScore}/100</span>
            </div>
            {brief.complexityDrivers.length > 0 && (
              <p className="bb-drivers">Driven by {brief.complexityDrivers.join(', ')}.</p>
            )}
          </div>
          <div className="bb-summary-cell bb-summary-cell--effort">
            <div className="bb-eyebrow">Effort</div>
            <div className="bb-effort-value">{brief.effort.timeframe}</div>
            <div className="bb-effort-team">{brief.effort.teamShape}</div>
          </div>
        </div>
      )}

      {/* ── Capabilities · build or buy ── */}
      {brief.capabilities.length > 0 && (
        <div className="bb-group">
          <div className="bb-eyebrow">Capabilities · build or buy</div>
          <div className="bb-caps">
            {brief.capabilities.map((c, i) => (
              <div className="bb-cap" key={`${c.name}-${i}`}>
                <div className="bb-cap-head">
                  <span className="bb-cap-name">{c.name}</span>
                  <span className={`bb-tag bb-tag--${c.buildOrBuy}`}>{c.buildOrBuy}</span>
                </div>
                <p className="bb-cap-desc">{c.description}</p>
                {c.recommendation && (
                  <div className="bb-cap-reco">
                    <span className="bb-cap-reco-label">Recommended</span>
                    {c.recommendation}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Foundation · vendor-neutral ── */}
      {brief.foundation.length > 0 && (
        <div className="bb-group">
          <div className="bb-eyebrow">Foundation · vendor-neutral</div>
          <p className="bb-group-intro">
            This is the foundation every major cloud gives you. Pick the one you are
            comfortable with, the shape stays the same.
          </p>
          <div className="bb-foundation">
            {brief.foundation.map((f, i) => (
              <div className="bb-prim" key={`${f.primitive}-${i}`}>
                <div className="bb-prim-head">
                  <span className="bb-prim-name">{f.primitive}</span>
                  <span className="bb-prim-clouds">{f.cloudExamples}</span>
                </div>
                <p className="bb-prim-why">{f.why}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── MVP scope ── */}
      {brief.mvpScope && (
        <div className="bb-group">
          <div className="bb-eyebrow">MVP scope</div>
          <p className="bb-mvp">{brief.mvpScope}</p>
        </div>
      )}

      {/* ── Technical risks ── */}
      {brief.technicalRisks.length > 0 && (
        <div className="bb-group">
          <div className="bb-eyebrow">Technical risks</div>
          <div className="bb-risks">
            {brief.technicalRisks.map((r, i) => (
              <div className="bb-risk" key={`${r.title}-${i}`}>
                <span className="bb-risk-index">R{i + 1}</span>
                <div className="bb-risk-body">
                  <div className="bb-risk-title">{r.title}</div>
                  <p className="bb-risk-desc">{r.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Foundations & limits ── */}
      <div className="bb-card bb-limits">
        <div className="bb-limits-header">Foundations &amp; Limits</div>
        <ul className="bb-principles">
          {FOUNDATION_PRINCIPLES.map(p => (
            <li className="bb-principle" key={p}>
              {p}
            </li>
          ))}
        </ul>
        <p className="bb-limit-statement">{LIMIT_STATEMENT}</p>
      </div>

      {/* ── Action row ── */}
      <div className="bb-actions">
        <div className="bb-actions-group">
          <button type="button" className="bb-action-btn" onClick={copyMarkdown}>
            {copied ? (
              <>
                <Check size={12} strokeWidth={2} aria-hidden />
                copied
              </>
            ) : (
              <>
                <Copy size={12} strokeWidth={2} aria-hidden />
                copy as markdown
              </>
            )}
          </button>
        </div>
        {generatedAt && (
          <span className="bb-generated">Generated {formatGeneratedAt(generatedAt)}</span>
        )}
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────────────────
   Pane — the Build Brief tab. Renders the matching state directly;
   no collapsible section, no header, no peek.
   ────────────────────────────────────────────────────────── */

export default function BuildBriefPane({ buildBrief, idea, onUpgrade }: Props) {
  const { status, brief, generatedAt, error, freeTaste, generate, dismissError } = buildBrief;

  if (status === 'locked') {
    return (
      <div className="bb-pane">
        <Invite locked onUpgrade={onUpgrade} />
      </div>
    );
  }

  if (status === 'idle') {
    return (
      <div className="bb-pane">
        <Invite freeTaste={freeTaste} onGenerate={generate} />
      </div>
    );
  }

  if (status === 'loading' || status === 'generating') {
    return (
      <div className="bb-pane">
        <SkeletonState />
      </div>
    );
  }

  if (status === 'error') {
    return (
      <div className="bb-pane">
        <ErrorState message={error ?? "Couldn't generate the brief."} onRetry={generate} />
      </div>
    );
  }

  return (
    <div className="bb-pane">
      {brief && (
        <BriefBody
          brief={brief}
          idea={idea}
          generatedAt={generatedAt}
        />
      )}
      {error && (
        <div className="bb-cap-msg" role="alert">
          <span>{error}</span>
          <button
            type="button"
            className="bb-cap-msg-dismiss"
            onClick={dismissError}
            aria-label="Dismiss"
          >
            ×
          </button>
        </div>
      )}
    </div>
  );
}
