import Foundation

/// Renders a Build Brief as plain markdown for copy/share. Dependency-free.
func buildBriefMarkdown(_ brief: BuildBrief) -> String {
    var lines: [String] = ["# Build Brief", ""]

    if brief.isTechDominant {
        lines.append("**Build complexity:** \(brief.complexityScore)/100 — \(brief.complexityLabel)")
        if !brief.complexityDrivers.isEmpty {
            lines.append("Driven by \(brief.complexityDrivers.joined(separator: ", ")).")
        }
        lines.append("**Effort:** \(brief.effort.timeframe) · \(brief.effort.teamShape)")
    } else {
        lines.append("**Not technology-dominant** — a website plus off-the-shelf payments gets you most of the way.")
    }
    lines.append("")

    // Skip a section entirely when it has no content (e.g. a low-tech brief),
    // so copied markdown never carries empty headers.
    if !brief.capabilities.isEmpty {
        lines.append("## Capabilities · build or buy")
        for c in brief.capabilities {
            lines.append("- **\(c.name)** (\(c.buildOrBuy.rawValue)): \(c.description)")
            if !c.recommendation.isEmpty { lines.append("  - Recommended: \(c.recommendation)") }
        }
        lines.append("")
    }

    if !brief.foundation.isEmpty {
        lines.append("## Foundation · vendor-neutral")
        for f in brief.foundation {
            lines.append("- **\(f.primitive)** — \(f.cloudExamples): \(f.why)")
        }
        lines.append("")
    }

    if !brief.mvpScope.isEmpty {
        lines.append("## MVP scope")
        lines.append(brief.mvpScope)
        lines.append("")
    }

    if !brief.technicalRisks.isEmpty {
        lines.append("## Technical risks")
        for (i, r) in brief.technicalRisks.enumerated() {
            lines.append("### R\(i + 1) — \(r.title)")
            lines.append(r.description)
        }
        lines.append("")
    }

    lines.append("## Foundations & Limits")
    for p in BuildBriefCopy.principles { lines.append("- \(p)") }
    lines.append("")
    lines.append("> \(BuildBriefCopy.limit)")
    lines.append("")
    lines.append("— Generated by plinths · Build Brief")

    return lines.joined(separator: "\n")
}
