import type { MarketMemo, ScoreBand } from './types';

const AXIS_LABEL: Record<ScoreBand['axis'], string> = {
  saturation:  'How crowded',
  difficulty:  'How hard to start',
  opportunity: 'Your opportunity',
};

/** Markdown export for the Market Memo — mirrors the on-page sections so a
 *  downloaded brief reads the same as the rendered memo. */
export function buildMemoMarkdown(memo: MarketMemo, briefId: string, dateStr: string): string {
  const lines: string[] = [];

  lines.push(`# ${memo.idea}`);
  lines.push('');
  lines.push(`**${briefId}** · ${dateStr} · ${memo.vertical}`);
  lines.push('');
  if (memo.oneliner) {
    lines.push(`> ${memo.oneliner}`);
    lines.push('');
  }

  lines.push('## The Read');
  lines.push('');
  if (memo.read.synthesis) lines.push(memo.read.synthesis);
  lines.push('');
  if (memo.read.recommendation) lines.push(`**What we'd do:** ${memo.read.recommendation}`);
  if (memo.read.limit) lines.push(`**Keep in mind:** ${memo.read.limit}`);
  lines.push('');

  lines.push('## Scores');
  lines.push('');
  for (const b of memo.bands) {
    lines.push(`- ${AXIS_LABEL[b.axis]} · ${b.score}/100 · ${b.label}`);
  }
  lines.push('');

  lines.push('## Market Size');
  lines.push('');
  lines.push(`${memo.marketSize.tam}${memo.marketSize.growth ? ` · ${memo.marketSize.growth}` : ''}`);
  if (memo.marketSize.note) lines.push(memo.marketSize.note);
  lines.push('');

  lines.push('## Competitive Landscape');
  lines.push('');
  for (const c of memo.competitors) {
    lines.push(`### ${c.name} · ${c.tier}`);
    if (c.strength) lines.push(`- Good at: ${c.strength}`);
    if (c.weakness) lines.push(`- Weak spot: ${c.weakness}`);
    const meta = [c.fundingStage, c.position].filter(Boolean).join(' · ');
    if (meta) lines.push(`- ${meta}`);
    lines.push('');
  }

  if (memo.whyNow.shift) {
    lines.push('## Why Now');
    lines.push('');
    lines.push(memo.whyNow.shift);
    lines.push('');
  }

  lines.push('## Market Gaps');
  lines.push('');
  memo.gaps.forEach((g, i) => {
    lines.push(`### Gap ${String(i + 1).padStart(2, '0')} · ${g.title} · ${g.severity} opportunity`);
    if (g.description) lines.push(g.description);
    if (g.underserved) lines.push(`Who's left out: ${g.underserved}`);
    if (g.tags.length) lines.push(`Tags: ${g.tags.join(', ')}`);
    lines.push('');
  });

  if (memo.entryCost.length) {
    lines.push('## What It Takes to Start');
    lines.push('');
    for (const f of memo.entryCost) {
      lines.push(`### ${f.label}`);
      if (f.value) lines.push(f.value);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`Generated by plinths · ${briefId}`);
  return lines.join('\n');
}
